language: ruby
cache: bundler
rvm:
  - 2.3.0
branches:
  only:
  - source # branch to build
addons:
  apt:
    packages:
      - jpegoptim
script:
  - jpegoptim --max=80 --strip-all -T5 -o source/images/{**/,**/**/}*.jpg
  - bundle exec middleman build
  - bundle exec htmlproof --allow-hash-href --only-4xx ./build
after_success:
  - echo ${GH_TOKEN} > ./.git/credentials
  - git config --global user.name ${GH_USER}
  - git config --global user.email ${GH_EMAIL}
  - git remote set-url origin "https://${GH_TOKEN}@github.com/lbischof/maplesplendor.ca.git"
  - bundle exec middleman deploy
  - curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" -H "X-Auth-Email: ${CF_EMAIL}" -H "X-Auth-Key: ${CF_TOKEN}" -H "Content-Type: application/json" --data '{"purge_everything":true}'
