title = "Maplesplendor"
theme = "ms"

DefaultContentLanguage = "de"

[params]
  # Shortcodes that must be closed
  # If the shortcode uses .Inner then add it here!
  mustCloseShortcodes = ["section"]

[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true

[menu]
[[menu.main]]
identifier = "cart"
name = "Cart"
url = "https://ww8.aitsafe.com/cf/review.cfm?userid=A4132041"
weight = 40

[[menu.footer]]
identifier = "cart"
name = "Cart"
url = "https://ww8.aitsafe.com/cf/review.cfm?userid=A4132041"
weight = 20

[[menu.footer]]
identifier = "contact"
name = "Contact"
url = "mailto: buy@maplesplendor.ca"
weight = 40
