backend:
  name: github
  repo: lbischof/ms
  branch: source

media_folder: source/images

collections:
  - name: pages
    label: Pages
    identifier_field: name
    folder: data/pages
    format: yml
    extension: yml
    editor:
      preview: false
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: 'Section'
        name: 'content'
        widget: 'list'
        typeKey: partial
        types:
          - label: 'Mals Multiple'
            name: 'mals-multiple'
            widget: object
            summary: '{{fields.product}}'
            fields:
              - label: Product
                name: product
                widget: string
              - label: Banner
                name: banner
                widget: boolean
              - label: Textboxes
                name: textboxes
                widget: boolean
              - label: "Description"
                name: "description"
                widget: markdown
              - label: Text Colour
                name: text_colour
                widget: string
              - label: Radios
                label_singular: Radio
                name: radios
                widget: list
                summary: '{{fields.name}} ${{fields.price}}'
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Price
                    name: price
                    valueType: float
                    widget: number
              - label: Colours
                label_singular: Colour
                minimize_collapsed: true
                name: colours
                widget: list
                summary: '{{fields.name}} (hide: {{fields.hide}})'
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Hide
                    name: hide
                    required: false
                    default: false
                    widget: boolean
