backend:
  name: github
  repo: lbischof/ms
  branch: source

media_folder: source/images

collections:
  - name: pages
    label: Pages
    identifier_field: name
    folder: data/pages
    format: yml
    extension: yml
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
    - label: 'Content'
      name: 'content'
      widget: 'list'
      typeKey: partial
      types:
        - label: 'Mals Multiple'
          name: 'mals-multiple'
          widget: object
          summary: '{{fields.product}}'
          fields:
            - label: Product
              name: product
              widget: string
            - label: Banner
              name: banner
              widget: boolean
            - label: Textboxes
              name: textboxes
              widget: boolean
