backend:
  name: github
  repo: lbischof/ms

media_folder: source/images

collections:
  - name: pages
    label: Pages
    identifier_field: title
    folder: data/pages
    format: yml
    extension: yml
    fields:
      - label: "Title"
        name: "title"
        widget: "string"


